services:
  web-nginx:
    image: nginx:alpine
    container_name: web-nginx
    restart: unless-stopped
    ports:
      - "8989:80"
    volumes:
      - ./src:/var/www/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      - php-site
    depends_on:
      - web-php

  web-php:
    image: php:8.3-fpm-alpine
    container_name: web-php
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    networks:
      - php-site

networks:
  php-site:
    driver: bridge