upstream api_pool {
    server api-test-1:7111;
    server api-test-2:7222;
    server api-test-3:7333;
}

server {
    listen 80;
    listen [::]:80;
    server_name _;

    location / {
        proxy_pass http://api_pool;
    }
}